/**
 * Contract Testing Utilities
 *
 * These utilities help verify that the frontend can deserialize
 * backend responses correctly. Fixtures are generated by the backend
 * during CI and copied to the fixtures/ directory.
 */

import fs from 'fs';
import path from 'path';

/**
 * Load a fixture file from the fixtures directory
 * @param name - Name of the fixture file (e.g., 'channel_reply_response.json')
 * @returns The fixture content as a string
 * @throws Error if fixture does not exist
 */
export function loadFixture(name: string): string {
  const fixturePath = path.join(__dirname, 'fixtures', name);
  if (!fs.existsSync(fixturePath)) {
    throw new Error(
      `Fixture not found: ${name}. ` +
      `Fixtures are generated by backend CI. ` +
      `Run backend fixture generation or check CI logs.`
    );
  }
  return fs.readFileSync(fixturePath, 'utf-8');
}

/**
 * Check if a fixture exists
 * @param name - Name of the fixture file
 * @returns true if fixture exists, false otherwise
 */
export function fixtureExists(name: string): boolean {
  const fixturePath = path.join(__dirname, 'fixtures', name);
  return fs.existsSync(fixturePath);
}

/**
 * Parse JSON fixture and return typed object
 * @param name - Name of the fixture file
 * @returns Parsed JSON object
 */
export function loadJsonFixture<T>(name: string): T {
  const content = loadFixture(name);
  return JSON.parse(content) as T;
}
