plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidLibrary)
}

// Read API base URL from gradle property or use default
val apiBaseUrl: String = project.findProperty("api.base.url") as? String
    ?: "https://api.chatmoderatorbot.ru"

// Derive auth domain from API base URL (replace api. with admin.)
val authDomain: String = apiBaseUrl
    .replace("https://api.", "https://admin.")
    .replace("https://chatmodtest.ru/api", "https://admin.chatmodtest.ru")
    .replace("/api", "") // Remove /api suffix if present

kotlin {
    androidTarget {
        compilations.all {
            kotlinOptions {
                jvmTarget = "17"
            }
        }
    }

    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "CoreCommon"
            isStatic = true
        }
    }

    jvm("desktop")

    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
    wasmJs {
        browser()
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation(libs.kotlinx.coroutines.core)
                api(libs.decompose)
                api(libs.essenty.lifecycle)
            }
            kotlin.srcDir("build/generated/buildconfig/commonMain/kotlin")
        }

        androidMain.dependencies {
        }

        iosMain.dependencies {
        }

        val desktopMain by getting {
            dependencies {
                implementation(libs.kotlinx.coroutines.swing)
            }
        }

        val wasmJsMain by getting {
            dependencies {
                // No additional dependencies needed - using JS interop
            }
        }
    }
}

android {
    namespace = "com.chatkeep.admin.core.common"
    compileSdk = 35

    defaultConfig {
        minSdk = 24
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

// Task to generate BuildConfigGenerated.kt
val generateBuildConfig by tasks.registering {
    val outputDir = file("$buildDir/generated/buildconfig/commonMain/kotlin")
    val outputFile = file("$outputDir/com/chatkeep/admin/core/common/BuildConfigGenerated.kt")

    outputs.file(outputFile)
    outputs.upToDateWhen { false } // Always regenerate to pick up property changes

    doLast {
        outputDir.mkdirs()
        outputFile.writeText("""
            package com.chatkeep.admin.core.common

            /**
             * Generated build configuration.
             * Do not edit manually - this file is generated by gradle task.
             */
            internal object BuildConfigGenerated {
                const val API_BASE_URL: String = "$apiBaseUrl"
                const val AUTH_DOMAIN: String = "$authDomain"
            }
        """.trimIndent())
    }
}

// Make Kotlin compilation depend on config generation
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateBuildConfig)
}
