package ru.andvl.chatkeep.domain.model.moderation

enum class ActionType {
    NOTHING,
    WARN,
    UNWARN,
    MUTE,
    UNMUTE,
    BAN,
    UNBAN,
    KICK,
    CLEAN_SERVICE_ON,
    CLEAN_SERVICE_OFF,
    LOCK_WARNS_ON,
    LOCK_WARNS_OFF,
    LOCK_ENABLED,
    LOCK_DISABLED,
    CONFIG_CHANGED,
    BLOCKLIST_REMOVED,
    // Mini App content changes
    WELCOME_CHANGED,
    RULES_CHANGED,
    TWITCH_CHANNEL_ADDED,
    TWITCH_CHANNEL_REMOVED,
    TWITCH_SETTINGS_CHANGED,
    CHANNEL_REPLY_CHANGED,
    ANTIFLOOD_CHANGED,
    BLOCKLIST_ADDED
}
