-- Fix chat_gated_features composite key by adding surrogate id
-- Recreate table to work with both PostgreSQL and H2

-- Create new table with surrogate id as primary key
CREATE TABLE chat_gated_features_new (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    feature_key VARCHAR(50) NOT NULL,
    enabled BOOLEAN DEFAULT false,
    enabled_at TIMESTAMP,
    enabled_by BIGINT
);

-- Copy existing data
INSERT INTO chat_gated_features_new (chat_id, feature_key, enabled, enabled_at, enabled_by)
SELECT chat_id, feature_key, enabled, enabled_at, enabled_by FROM chat_gated_features;

-- Drop old table
DROP TABLE chat_gated_features;

-- Rename new table
ALTER TABLE chat_gated_features_new RENAME TO chat_gated_features;

-- Add unique constraint on composite key
CREATE UNIQUE INDEX uq_chat_gated_features_chat_feature ON chat_gated_features(chat_id, feature_key);

-- Recreate index
CREATE INDEX idx_gated_features_chat ON chat_gated_features(chat_id);
